apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{PLUGIN_NAME}}
spec:
  selector:
    matchLabels:
      app: {{PLUGIN_NAME}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{PLUGIN_NAME}}
    spec:
      containers:
      - name: nginx
        image: 10.0.0.24:443/image:{{DRONE_COMMIT_SHA}}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
